@startuml TabelaER


class OrdemFabrico {
}   

class Produto {
}

class MateriaPrima {
}

class FichaTecnica {
}

class Operacao {
}

class SubContratado {
}

<> EtapaProducao

<> EtapasOrdem

/'
Relacionamento Etapa Producao
'/
EtapaProducao }|--|| FichaTecnica: Etapas Produção
EtapaProducao }o--|| Operacao: Operacoes Necessarias
EtapaProducao }o--|| MateriaPrima: Materiais Necessarios

/'
Relacionamento da Etpas da Ordem
'/
SubContratado ||--o{ EtapasOrdem: Pode possuir
EtapasOrdem ||--|{ EtapaProducao: Possui
OrdemFabrico ||--|{ EtapasOrdem: faz parte de

/'
Relacionamentos do Produto
'/
Produto ||--o{ FichaTecnica: descreve

@enduml