@startuml tableBD

/'
Diz todas as operacoes, todos os materiais enviados 
e todos os materiais obtidos
'/
class FichaTecnica {
    codigo 
    name 
    ProdutoFinal
    ProdutosObtidos 
    MateriasPrimas 
    Operacoes
}

class Produto {
    codigo 
    nome
    stock 
}

class Operacao {
    codigo 
    nome
}

class OrdemFabrico {

}

FichaTecnica }o--|{ Operacao: Operacoes


class MateriaisFichaTecnica{
    codigoFicha
    codigoProduto
    quantidadeUtilizada
    unidade
}

class ProdutosObtidosFichaTecnica{
    codigoFicha
    codigoProduto
    quantidadeObtida
    unidade
}

FichaTecnica ||--|{ MateriaisFichaTecnica: Utiliza 
Produto ||--o{ MateriaisFichaTecnica: Utiliza 

FichaTecnica ||--|{ ProdutosObtidosFichaTecnica: Pordutos Obtidos 
Produto ||--o{ ProdutosObtidosFichaTecnica: Pordutos Obtidos 

Produto ||--o{ FichaTecnica: Produto Final
@enduml