@startuml tableBD
/'
Meter tabela de fornecedor 
ligado aos Materias e 
OperacaoSubContratada
'/

/'
Agregações:
Funcionario com Departamento
Departamento com OperaçãoInterna
FichaTecnica com Operacao

Composições:
Produto com Ordem de fabrico
Cliente com Ordem de fabrico
Produto com Ficha Tecnica
OperacaoSubContratada com Operacao
OperacaoInterna com Operacao
'/

/'
Define os produtos a fabricar,
Quantidades necessárias
Prazos de conclusão
'/
class OrdemFabrico {
    string cod_ordem
}   

class Produtos {
    string codProduct
    string codOpContratados
}

class ProdutoOrdemFabrico {
    string cod_ordem
    string codProduct
}

/'
Conjunto de operações necessarias para a produção
de um produto
'/
class FichaTecnica {
    string codFicha
}

class FichaTecnicaOperacao {
    string codFicha
    string codOpContratados
}


/'
Materias utilizados nas operacoes;
'/
class Materiais {
    string codMaterial 
}

/'
Parceiro externo que pode desenvolver uma operação
Ver se apenas um subContratado pode fazer uma e so uma operação
'/
class Operacao {
    string codOp
}

class OperacaoSubContratados {
    string codOpContratados
}

/'Operacoes feitas pelo propria empresa'/
class OperacaoInterna {
    string codOpInt
}

class OperacaoInternaMaterial {
    strin codOpInt
    string codMaterial
}

/'Extras se quissermos complicar'/

/'Setor da fabrica responsável por uma determinada
operacao'/
class Departamento {
    string codDep
}

/'
Funcionario da fabrica, que faz parte de um setor
'/
class Funcionario {
    int codF
}

class Cliente {
    string codCl
}

/'
Relacionamento dos Funcionarios
'/
Funcionario }|--|| Departamento: pertence
Funcionario ||--o{ Departamento: supervisiona 


/'
Relacionamento Operacao
'/
Operacao ||--o{ OperacaoInterna: Tipo Interna
Operacao ||--o{ OperacaoSubContratados: Tipo Sub Contratada
Operacao ||--o{ FichaTecnicaOperacao: Operacoes da Ficha Tecnica
/'

Relacionamento das Operacoes Interna
'/
OperacaoInterna ||--|| Departamento: Operacao do Departamento
OperacaoInterna ||---o{ OperacaoInternaMaterial: Necessita

/'
Relacionamento Materiais
'/
Materiais ||---o{ OperacaoInternaMaterial: Pertence

/'
Relacionamento da Ficha Tecnica
'/

FichaTecnica ||---o{ FichaTecnicaOperacao: Operacoes
/'
Relacionamentos do Produto
'/
Produtos ||--|| FichaTecnica: Possui
Produtos ||---o{ProdutoOrdemFabrico

/'
Relacionamento Ordem Fabrico
'/
OrdemFabrico ||--|{ ProdutoOrdemFabrico
Cliente ||--|{ OrdemFabrico: pede
@enduml