@startuml tableBD
/'
Segundo o Bruno Materiais vão ser também produtos
'/

/'
Meter tabela de fornecedor 
ligado aos Materias e 
OperacaoSubContratada
'/

/'
Agregações:
Funcionario com Departamento
Departamento com OperaçãoInterna
FichaTecnica com Operacao

Composições:
Produto com Ordem de fabrico
Cliente com Ordem de fabrico
Produto com Ficha Tecnica
OperacaoSubContratada com Operacao
OperacaoInterna com Operacao
'/

/'
Define os produtos a fabricar,
Quantidades necessárias
Prazos de conclusão
'/
class OrdemFabrico {
    ManufacturingNo ManufacturingNo
}   

class Produtos {
    ProductNo ProductNo
}

class Stock {
    StockNo StockNo
}

class ProdutoQuantidade {
}

/'
Conjunto de operações necessarias para a produção
de um produto
'/
class FichaTecnica {
    FichTecNo FichTecNo
}

class FichaTecnicaOperacao {
}


/'
Parceiro externo que pode desenvolver uma operação
Ver se apenas um subContratado pode fazer uma e so uma operação
'/
class Operacao {
    OpNo OpNo
}

class OperacaoProduto { 
}

/'Extras se quissermos complicar'/

/'Setor da fabrica responsável por uma determinada
operacao'/
class Departamento {
    DeptNo DeptNo 
}

/'
Funcionario da fabrica, que faz parte de um setor
'/
class Funcionario {
    FuncNo FuncNo
}

class Cliente {
    ClientNo ClientNo 
}

class Fornecedor {
    string FornNo 
}

/'
Relacionamento dos Funcionarios
'/
Funcionario }|--|| Departamento
Funcionario ||--o{ Departamento 

/'
Relacionamento do Fornecedor
'/
Fornecedor |o--o{ Produtos
Fornecedor |o--o{ Operacao

/'
Relacionamento Operacao
'/
Operacao ||--o{ FichaTecnicaOperacao

/'
Relacionamento das Operacoes Interna
'/
Operacao ||--o| Departamento
Operacao |o---o{ OperacaoProduto

/'S
Relacionamento Materiais
'/
Produtos |o---o{ OperacaoProduto
Produtos ||--|| Stock
/'
Relacionamento da Ficha Tecnica
'/
FichaTecnica ||---o{ FichaTecnicaOperacao

/'
Relacionamentos do Produto
'/
Produtos ||--|| FichaTecnica
Produtos ||---o{ ProdutoQuantidade

/'
Relacionamento Ordem Fabrico
'/
OrdemFabrico ||--|{ ProdutoQuantidade
Cliente ||--o{ OrdemFabrico

@enduml