@startuml tableBD

class OrdemFabrico {
    ManufacturingNo ManufacturingNo
}   

class Produto {
    ProductNo ProductNo
}

class FichaTecnica {
    FichTecNo FichTecNo
}

class Operacao {
    OpNo OpNo 
}

class SubContratado {
    SubContratado SubContratado
}

class Departamento {
    DeptNo DeptNo 
}

class Funcionario {
    FuncNo FuncNo
}

class Cliente {
    ClientNo ClientNo
}

/'
Relacionamento dos Funcionarios
'/
Funcionario }|--o| Departamento: Possui
Funcionario ||--o{ Departamento: SuperVisiona 

/'
Relacionamento das Operacoes Interna
'/
Operacao }|--o| Departamento: Realiza(da)

/'
Relacionamento Ficha Tecnica
'/
FichaTecnica }o--|{ Operacao
FichaTecnica }o--|{ Produto: Utiliza(do)

/'
Relacionamentos do Produto
'/
Produto |o--o{ FichaTecnica: Possui
Produto }o--o{ OrdemFabrico

/'
Relacionamento Ordem Fabrico
'/
OrdemFabrico }o--o| Cliente: Contrata
OrdemFabrico }o--o{ SubContratado

@enduml