@startuml tableBD

class OrdemFabrico {
    ManufacturingNo ManufacturingNo
}   

class MateriaPrima{
    MateriaPrimaNo materiaPrimaNo
}

class Produto {
    ProductNo ProductNo
}

class FichaTecnica {
    FichTecNo FichTecNo
}

class Operacao {
    OpNo OpNo 
}

class SubContratado {
    SubContratado SubContratado
}

class Departamento {
    DeptNo DeptNo 
}

class Funcionario {
    FuncNo FuncNo
}

class Cliente {
    ClientNo ClientNo
}

/'
Relacionamento dos Funcionarios
'/
Funcionario }|--o| Departamento: Possui
Funcionario ||--o{ Departamento: SuperVisiona 

/'
Relacionamento das Operacoes Interna
'/
Operacao }|--o| Departamento: Realiza(da)
Operacao }o--|{ MateriaPrima: Materiais Utilizados
Operacao }o--|| Produto: Produto Final

/'
Relacionamento Ficha Tecnica
'/
FichaTecnica }o--|{ Operacao
FichaTecnica }o--|{ MateriaPrima: Utiliza(do)
FichaTecnica }o--o{ OrdemFabrico
FichaTecnica }o--|| Funcionario: ResponsavelFicha
/'
Relacionamentos do Produto
'/
Produto ||--|| FichaTecnica: Produto Final

/'
Relacionamento Ordem Fabrico
'/
OrdemFabrico }o--o| Cliente: Contrata
OrdemFabrico }o--o{ SubContratado

@enduml