@startuml tableBD

/'
!Meter realções ternarias
!Ligação da ORdem de Fabrico e Produto mal, o que liga é a ficha Tecnica
'/

class OrdemFabrico {
    ManufacturingNo ManufacturingNo
}   

/'
O stock é quantidade que tem de Produto
O fornecedor vai ter os campos da tabela e o Produto 
pode ter varios

Talvez haja uma tabela materiais que liga juntamente
ao Produto há tabela operação

ProductionType --> Acabado ou SemiAcabado 
'/
class Produto {
    ProductNo ProductNo
}

class MateriaPrima {
    MateriaNo materiaNo
}

class Stock {
    StockNo stockNo
}

class Perda {
    PerdaNo perdaNo 
}

/'
Conjunto de operações necessarias para a produção
de um Produto, os materiais utilizados e o resultado 
final
'/
class FichaTecnica {
    FichTecNo FichTecNo
}

/'
Parceiro externo que pode desenvolver uma operação
Ver se apenas um subContratado pode fazer uma e so uma operação
'/
class Operacao {
    OpNo OpNo 
}

/'
ExpectedTime, acho que é o unico que não é preciso

O subContratado ele manda tudo, o que está bem, mal, etc.

O productNo seria os materias que enviamos
'/
class SubContratado {
    SubContratado SubContratado
}

class Fornecedor {
    FornNo codForn 
}

/'Extras se quissermos complicar'/

/'Setor da fabrica responsável por uma determinada
operacao'/
class Departamento {
    DeptNo DeptNo 
}

/'
Funcionario da fabrica, que faz parte de um setor
'/
class Funcionario {
    FuncNo FuncNo
}

class Cliente {
    ClientNo ClientNo
}

/'
Relacionamento do Stock
'/
Produto ||--|| Stock
MateriaPrima ||--||Stock

/'
Relacionamento dos Funcionarios
'/
Funcionario }|--o| Departamento: Possui
Funcionario ||--o{ Departamento: SuperVisiona 

/'
Relacionamento das Operacoes Interna
'/
Operacao }|--o| Departamento: Realiza(da)
Operacao }o--|{ MateriaPrima: Materiais Utilizados
Operacao }o--|| Produto: Produto Final

/'
Relacionamento Ficha Tecnica
'/
FichaTecnica }o--|{ Operacao
FichaTecnica }o--|{ MateriaPrima: Utiliza(do)
FichaTecnica }o--o{ OrdemFabrico
FichaTecnica }o--|| Funcionario: ResponsavelFicha
/'
Relacionamentos do Produto
'/
Produto ||--|| FichaTecnica: Produto Final


/'
Relacionamento de MateriaisSubContratados
'/

MateriaPrima ||--o{ MateriaisSubContrato: Enviado
SubContratado ||--|{ MateriaisSubContrato: Necessita
Produto ||--o{ MateriaisSubContrato: Recebido

/'
Relacionamento do Fornecedor
'/
SubContratado }o-|| Fornecedor: Fornecedor

/'
Relacionamento Ordem Fabrico
'/
OrdemFabrico }o--o| Cliente: Contrata
OrdemFabrico }o--o{ SubContratado
OrdemFabrico ||--o{ Perda

@enduml