@startuml Normalizacao

class OrdemFabrico {
    ManufacturingNo ManufacturingNo
    nvarchar[9] Status 
    DateTime CreationDate
    DateTime StarDate
    DateTime EndDate
    number Priority
    nvarchar[250] Obs
    number CostCharged
}

class LinhasFichaTecnicas {
    ManufacturingNo ManufacturingNo
    FichTecNo FichTecNo
    number quantidadeProduzir
    number quantidadePerdas
}

class LinhasSubContratos {
    ManufacturingNo ManufacturingNo
    SubContratado SubContratado
    number price 
    number quantidadeProduzir
    number quantidadePerdas
    dateTime expectedTime
}

class SubContratado {
    SubContratado SubContratado
    nvarchar[50] name
    nvarchar[100] Obs
    MaterialNo materialFinal
}


class FichaTecnica {
    FichTecNo FichTecNo
    ProductNo ProductNo 
    number ProductionCost   
    nvarchar[250] Obs
}

class EtapaProducao {
    FichTecNo FichTecNo
    OpNo OpNo
    MateriaNo MaterialFinal
    time TempoEsperado
    number QuantidadeProduzir
    number DiscardedAmount
}


class Operacao {
    OpNo OpNo 
    nvarchar[30] Name 
    nvarchar[250] Obs
}

class MateriaPrima {
    MateriaNo materiaNo
    nvarchar[30] Name 
    number PriceUnitario
    number stock 
    string unidadeStock
    nvarchar[250] Obs
}

class MaterialEnviado {
    SubContratadoNo SubContratado
    MaterialNo MaterialNo
    number quantidadeEnviada
}


class Produto {
    ProductNo ProductNo
    nvarchar[30] Name 
    number PriceUnitario 
    nvarchar[20] ProductType
    nvarchar[250] Descricao
    nvarchar[9] Genero
    nvarchar[5] Tamanho
    number Peso
    number stock 
    string unidadeStock
}

/'
Relacionamentos do Produto
'/
Produto ||-o{ FichaTecnica: Produto

/'
Quantidade necessaria
'/
EtapaProducao }|--|| FichaTecnica
EtapaProducao }o-|| Operacao
EtapaProducao }o-|| MateriaPrima

/'
Relacionamento Intermediario Material Enviado ao SubContrato
'/
MaterialEnviado }|--|| SubContratado: Material Enviado
MaterialEnviado }o--|| MateriaPrima: Material Enviado

/'
Relacionamento SubContrato
'/
SubContratado }o--|| MateriaPrima: Produto Final

/'
Relacionamento da Ordem de Fabrico
'/
LinhasFichaTecnicas }o-|| FichaTecnica
LinhasFichaTecnicas }|--|| OrdemFabrico

LinhasSubContratos }o--|| SubContratado
LinhasSubContratos }|--|| OrdemFabrico

@enduml