@startuml teste 


class OrdemFabrico {
    ManufacturingNo ManufacturingNo
    DateTime CreationDate
    DateTime StarDate
    DateTime EndDate
    DateTime ExpectedEndDate
    int TotTimeExpected 
    int TotCostSubContract
    int Priority
    nvarchar[9] Status 
    nvarchar[250] Obs
}

class MateriaPrima {
    MateriaNo materiaNo
    nvarchar[30] Name
    float PriceUn
    int stock 
    nchar[5] unityStock
    nvarchar[250] Obs
}

class Operacao {
    OpNo OpNo
    nvarchar[30] Name 
    nvarchar[250] Obs
}

class SubContratado {
    SubContratado SubContratado
    nvarchar[30] name
    nvarchar[250]
}

class FichaTecnica {
    FichTecNo FichTecNo 
    ProductNo ProductNo
    nvarchar[250] Obs
}

class Produto {
    ProductNo ProductNo
    nvarchar[30] Name 
    float PriceUn
    nvarchar[20] ProductType
    nvarchar[250] Description
    nchar[1] Genero
    nchar[5] Sizes
    float Weight
    int stock 
    nvarchar[5] unityStock
}


class EtapaProducao {
    FichTecNo FichTecNo
    OpNo OpNo
    MateriaNo Material
    Type Type
}

/'
Verficiar se o MAterial e sempre um Material Final
'/
class EtapaOrdemFabrico {
    FichTecNo FichTecNo
    OpNo OpNo
    int QuantityMaterialOp
    int QuantityLost
    SubContratado OpSubNo
    int QuantityMaterialSub
    int QuantityReceivedSub
    int QuantityLost
    float PriceSub
    MateriaNo materiaNo
    Type Type
    int TotQuantity 
    int TotQuantityLost 
    int Priority 
    int TimeInMinutes 
    nchar[1] Status
    int Ordem
}

/'
Etapa Producao Interna
'/
EtapaProducao }|--|| FichaTecnica: Deifinida
EtapaProducao }o--|| MateriaPrima: Utiliza(do)
EtapaProducao }o--|| Operacao: Executa(da)

/'
Etapas da Ordem de Fabrico
'/
EtapaOrdemFabrico }o--|| OrdemFabrico: faz parte de
EtapaOrdemFabrico }o--|| EtapaProducao: inclui etapa interna
EtapaOrdemFabrico }o--o| SubContratado: pode incluir subContratados

FichaTecnica }o--|| Produto: descreve

/'
Listar Ordens em atraso com o respetivo tempo de atraso
'/
OrdemFabrico ---> OrdemFabrico: (a)

/'
Listar Operacoes Problematicas
'/
EtapaOrdemFabrico ---> EtapaProducao: (b)
EtapaProducao ---> Operacao: (b)

/'Custos Comparativos entre operação interna e externa'/
OrdemFabrico ---> EtapaOrdemFabrico: (c)
EtapaOrdemFabrico ---> SubContratado: (c)
EtapaOrdemFabrico ---> EtapaProducao: (c)

/'
Consultar as Ordens de fabrico em curso com indicação do progresso
'/
OrdemFabrico ---> EtapaOrdemFabrico: (d)

/'
Relatorio de operacoes com perdas superiores a 15%
'/
EtapaOrdemFabrico ---> EtapaProducao: (e)
EtapaProducao ---> Operacao: (e)

/'
Listar as Operacoes mais frequentemente subContratadas e respetivos custos
'/
EtapaOrdemFabrico ---> SubContratado: (f)

/'
Determinar o custo total de produção de uma ordem
'/
OrdemFabrico ---> EtapaOrdemFabrico: (g)
EtapaOrdemFabrico ---> SubContratado: (g)
EtapaOrdemFabrico ---> EtapaProducao: (g)
EtapaProducao ---> MateriaPrima: (g)

/'
Consultar lista de operacoes pendentes para cada ordem, ordenadas por prioridade
'/
OrdemFabrico ---> EtapaOrdemFabrico: (h)

/' 
Estimar o tempo total necessários para concluir uma ordem, com base no tempo médio das operações
'/
OrdemFabrico ---> EtapaOrdemFabrico: (i)
EtapaOrdemFabrico ---> EtapaProducao: (i)
EtapaProducao ---> Operacao: (i)

/'
Calcular a eficiência média de produção por período
'/
OrdemFabrico ---> EtapaOrdemFabrico: (j)
@enduml