@startuml tableBD

/'
!Meter realções ternarias
!Ligação da ORdem de Fabrico e Produto mal, o que liga é a ficha Tecnica
'/

/'Estes valores
int ExpectedQuantity
    int MadeAmount
    int DiscardedAmount
são comuns para a ordem e subContratado'/
class OrdemFabrico {
    ManufacturingNo ManufacturingNo

    int ExpectedQuantity
    int MadeAmount
    int DiscardedAmount

    nvarchar[9] Status 
    DateTime CreationDate
    DateTime StarDate
    DateTime EndDate
    number Priority
    nvarchar[250] Obs
    number CostCharged
}   

/'
O stock é quantidade que tem de Produto
O fornecedor vai ter os campos da tabela e o Produto 
pode ter varios

Talvez haja uma tabela materiais que liga juntamente
ao Produto há tabela operação

ProductionType --> Acabado ou SemiAcabado 
'/
class Produto {
    ProductNo ProductNo
    nvarchar[30] Name 
    number PriceUnitario 
    nvarchar[20] ProductType
    nvarchar[20] ProductionType
    nvarchar[250] Descricao
    nvarchar[9] Genero
    number stock 
    string unidadeStock
}

class MateriaPrima {
    MateriaNo materiaNo
    nvarchar[30] Name 
    number stock 
    string unidadeStock
}

/'
Conjunto de operações necessarias para a produção
de um Produto, os materiais utilizados e o resultado 
final
'/
class FichaTecnica {
    FichTecNo FichTecNo
    number quantidadeNecessariaEsperada
    nvarchar[5] Tamanho
    number Peso
    nvarchar[30] cor
    nvarchar[250] Obs
}

/'
Parceiro externo que pode desenvolver uma operação
Ver se apenas um subContratado pode fazer uma e so uma operação
'/
class Operacao {
    OpNo OpNo 
    Type type 
    nvarchar[30] Name 
    nvarchar[250] Obs
}

/'
ExpectedTime, acho que é o unico que não é preciso

O subContratado ele manda tudo, o que está bem, mal, etc.

O productNo seria os materias que enviamos
'/
class SubContratado {
    SubContratado SubContratado
    number price 
    dateTime expectedTime 
}

class Fornecedor {
    FornNo codForn 
    nvarchar[50] name
    PhoneNumber PhoneNumber
    char[50] email
    nvarchar[150] address
}

/'Extras se quissermos complicar'/

/'Setor da fabrica responsável por uma determinada
operacao'/
class Departamento {
    DeptNo DeptNo 
    nvarchar[30] Name
}

/'
Funcionario da fabrica, que faz parte de um setor
'/
class Funcionario {
    FuncNo FuncNo
    nvarchar[20] Fname
    nvarchar[20] Lname
    Sex Sex
    nvarchar[25] Position
    number Salary
    PhoneNumber PhoneNumber 
    char[50] email
    nvarchar[150] Address
    date DOB
}

class Cliente {
    ClientNo ClientNo
    nvarchar[20] Fname
    nvarchar[20] Lname
    Sex Sex
    number NIF 
    PhoneNumber PhoneNumber 
    char[50] email
    nvarchar[150] Address 
    date DOB
    nvarchar[11] Type
}

/'
Relacionamento dos Funcionarios
'/
Funcionario }|--o| Departamento: Possui
Funcionario ||--o{ Departamento: SuperVisiona 

/'
Relacionamento das Operacoes Interna
'/
Operacao }|--o| Departamento: Realiza(da)
Operacao }o--|{ MateriaPrima: Materiais Utilizados
Operacao }o--|| Produto: Produto Final

/'
Relacionamento Ficha Tecnica
'/
FichaTecnica }o--|{ Operacao
/'
FichaTecnica }o--|{ MateriaPrima: Utiliza(do)
'/
FichaTecnica }o--o{ OrdemFabrico
FichaTecnica }o--|| Funcionario: ResponsavelFicha
/'
Relacionamentos do Produto
'/
Produto ||--|| FichaTecnica: Produto Final

/'
Relacionamento do Fornecedor
'/
SubContratado }o-|| Fornecedor: Fornecedor

/'
Relacionamento Ordem Fabrico
'/
OrdemFabrico }o--o| Cliente: Contrata
OrdemFabrico }o--o{ SubContratado

@enduml