@startuml tableBD

/'
Falta SubContratados, subContratos
'/


/'
Ainda é o concetual
'/


/'
Agregações:
Funcionario com Departamento
Departamento com OperaçãoInterna
FichaTecnica com Operacao

Composições:
Produto com Ordem de fabrico
Cliente com Ordem de fabrico
Produto com Ficha Tecnica
OperacaoSubContratada com Operacao
OperacaoInterna com Operacao
'/

/'
Define os Produto a fabricar,
Quantidades necessárias
Prazos de conclusão

int ExpectedQuantity
int MadeAmount
int DiscardedAmount (Este 3 atributos diz respeito a quantidade produzida por produto)

'/
class OrdemFabrico {
    ManufacturingNo ManufacturingNo
    float ProductionCost
    float CostCharged
    string Status 
    DateTime CreationDate
    DateTime StarDate
    DateTime EndDate
    String Priority
    float perdas 
    string unidadePerdas
    int ExpectedQuantity
    int MadeAmount
    int DiscardedAmount
    string Obs
}   

/'
O stock é quantidade que tem de produto
O fornecedor vai ter os campos da tabela e o produto 
pode ter varios

Talvez haja uma tabela materiais que liga juntamente
ao produto há tabela operação
'/
class Produto {
    ProductNo ProductNo
    string Name 
    float Price 
    string ProductType
    FichTecNo FichTecNo
    string Descricao
    string Genero
    float stock 
    string unidadeStock
    string fornecedor 
}

/'
Conjunto de operações necessarias para a produção
de um produto
'/
class FichaTecnica {
    FichTecNo FichTecNo
    FuncNo TecnicoResp 
    OpNo Operacoes
    string Tamanho
    float Peso
    float Perdas
    string Obs
}

/'
Penso que o setor não quer isto, ele vai querer
secalhar que em vez disto, liguemos o produto e a 
operacao diretamente ha ordem de Fabrico
'/
class FichaTecnicaOperacao {
    FichTecNo FichTecNo
    OpNo OpNo
}

/'
Parceiro externo que pode desenvolver uma operação
Ver se apenas um subContratado pode fazer uma e so uma operação
'/
class Operacao {
    OpNo OpNo 
    Type type 
    string Name 
    string Obs
    float percentagem
    sfloat perdas 
    string unidadePerdas
}

/'
Se a fabrica embia materiais para eles, 
deve ter um campo para isso.
'/
class SubContrato {
    SubContrato subContrato
    string produtoDesenvolver
    string fornecedor 
    Date duracao
    string Obs
    string preco
    float quantidadeDesenvolvida
}


/'Extras se quissermos complicar'/

/'Setor da fabrica responsável por uma determinada
operacao'/
class Departamento {
    DeptNo DeptNo 
    string Name 
}

/'
Funcionario da fabrica, que faz parte de um setor
'/
class Funcionario {
    FuncNo FuncNo
    string DeptNo 
    string Fname 
    string Lname 
    Sex Sex
    string Position
    float Salary
    number PhoneNumber 
    string Email 
    string Address
    date DOB
}

class Cliente {
    ClientNo ClientNo
    string Fname
    string Lname
    Sex Sex
    number NIF 
    number PhoneNumber 
    string Email
    string Address 
    date DOB 
    string Type  
}

/'
Vai estar dentro do Produto
class Fornecedor {
    string FornNo 
    string Name 
    number PhoneNumber
    string Email 
    string Address
    string Type 
}

'/

/'
Relacionamento dos Funcionarios
'/
Funcionario }|--|| Departamento: Possui
Funcionario ||--o{ Departamento: SuperVisiona 

/'
Relacionamento Operacao
'/
Operacao ||--o{ FichaTecnicaOperacao: Faz parte

/'
Relacionamento Perdas
'/

/'
Relacionamento das Operacoes Interna
'/
Operacao ||--o| Departamento: Realiza(da)

/'S
Relacionamento Materiais
'/
Produto }o---o{ FichaTecnicaOperacao: Usado

/'
Relacionamento da Ficha Tecnica
'/
FichaTecnica ||---o{ FichaTecnicaOperacao: Possui

/'
Relacionamentos do Produto
'/
Produto ||--|| FichaTecnica: Possui
Produto }o---o{ OrdemFabrico

/'
Relacionamento Ordem Fabrico
'/
Cliente ||--o{ OrdemFabrico: Contrata

@enduml