@startuml tableBD

/'
Falta SubContratados, SubContratados
'/


/'
Ainda é o concetual
'/


/'
Agregações:
Funcionario com Departamento
Departamento com OperaçãoInterna
FichaTecnica com Operacao

Composições:
Produto com Ordem de fabrico
Cliente com Ordem de fabrico
Produto com Ficha Tecnica
OperacaoSubContratada com Operacao
OperacaoInterna com Operacao
'/

/'
Define os Produto a fabricar,
Quantidades necessárias
Prazos de conclusão

int ExpectedQuantity
int MadeAmount
int DiscardedAmount (Este 3 atributos diz respeito a quantidade produzida por produto)

'/
class OrdemFabrico {
    ManufacturingNo ManufacturingNo
    OpNo SubContratados
    ProductNo ProductNo
    int ExpectedQuantity
    int MadeAmount
    int DiscardedAmount
    PerdaNo perdaNo 
    nvarchar[50] name 
    number percentagem 
    number valorPerda
    nvarchar[5] unidade
    number ProductionCost
    number CostCharged
    nvarchar[9] Status 
    DateTime CreationDate
    DateTime StarDate
    DateTime EndDate
    number Priority
    nvarchar[250] Obs
}   

/'
O stock é quantidade que tem de produto
O fornecedor vai ter os campos da tabela e o produto 
pode ter varios

Talvez haja uma tabela materiais que liga juntamente
ao produto há tabela operação
'/
class Produto {
    ProductNo ProductNo
    nvarchar[30] Name 
    number Price 
    nvarchar[20] ProductType
    FichTecNo FichTecNo
    nvarchar[250] Descricao
    nvarchar[9] Genero
    StockNo stockNo
    number stock 
    string unidadeStock
}

class ProdutoOrdermFabrico {
    ProductNo ProductNo 
    FichaTecnicaNo FichaTecnicaNo
    ManufacturingNo ManufacturingNo
}

/'
Conjunto de operações necessarias para a produção
de um produto
'/
class FichaTecnica {
    FichTecNo FichTecNo
    FuncNo TecnicoResp 
    OpNo Operacoes
    ProductNo Materiais
    nvarchar[5] Tamanho
    number Peso
    number Perdas
    nvarchar[30] cor
    nvarchar[250] Obs
}

/'
Parceiro externo que pode desenvolver uma operação
Ver se apenas um subContratado pode fazer uma e so uma operação
'/
class Operacao {
    OpNo OpNo 
    Type type 
    nvarchar[30] Name 
    nvarchar[250] Obs
}

/'
ExpectedTime, acho que é o unico que não é preciso
'/
class SubContratado {
    SubContratado SubContratado
    FornNo codForn 
    nvarchar[50] name
    PhoneNumber PhoneNumber
    char[50] email
    nvarchar[150] address
    number price 
    dateTime expectedTime 
}


/'Extras se quissermos complicar'/

/'Setor da fabrica responsável por uma determinada
operacao'/
class Departamento {
    DeptNo DeptNo 
    nvarchar[30] Name
    FuncNo SupVisNo 
}

/'
Funcionario da fabrica, que faz parte de um setor
'/
class Funcionario {
    FuncNo FuncNo
    DeptNo DeptNo 
    nvarchar[20] Fname
    nvarchar[20] Lname
    Sex Sex
    nvarchar[25] Position
    number Salary
    PhoneNumber PhoneNumber 
    char[50] email
    nvarchar[150] Address
    date DOB
}

class Cliente {
    ClientNo ClientNo
    nvarchar[20] Fname
    nvarchar[20] Lname
    Sex Sex
    number NIF 
    PhoneNumber PhoneNumber 
    char[50] email
    nvarchar[150] Address 
    date DOB 
    nvarchar[11] Type  
}

/'
Relacionamento dos Funcionarios
'/
Funcionario }|--o| Departamento: Possui
Funcionario ||--o{ Departamento: SuperVisiona 

/'
Relacionamento das Operacoes Interna
'/
Operacao }|--o| Departamento: Realiza(da)

/'
Relacionamento Ficha Tecnica
'/
FichaTecnica }o--|{ Operacao
FichaTecnica }o--|{ Produto: Utiliza(do)

/'
Relacionamentos do Produto
'/
Produto |o--o{ FichaTecnica: Possui
Produto }o--o{ OrdemFabrico

/'
Relacionamento Ordem Fabrico
'/
OrdemFabrico }o--o| Cliente: Contrata
OrdemFabrico }o--o{ SubContratado

@enduml