@startuml tableBD

/'
!Ligação da ORdem de Fabrico e Artigo mal, o que liga é a ficha Tecnica
'/
/'
Falta SubContratados, SubContratados
'/


/'
Ainda é o concetual
'/


/'
Agregações:
Funcionario com Departamento
Departamento com OperaçãoInterna
FichaTecnica com Operacao

Composições:
Artigo com Ordem de fabrico
Cliente com Ordem de fabrico
Artigo com Ficha Tecnica
OperacaoSubContratada com Operacao
OperacaoInterna com Operacao
'/

/'
Define os Artigo a fabricar,
Quantidades necessárias
Prazos de conclusão

int ExpectedQuantity
int MadeAmount
int DiscardedAmount (Este 3 atributos diz respeito a quantidade produzida por Artigo)

Ver se a quantidade do subContrato está vem, ou então não.
'/
class OrdemFabrico {
    ManufacturingNo ManufacturingNo
    ProductNo ProductNo
    FichaTecnicaNo FichatTecnincaNo
    int quantidadeFabrica
    int DiscardedAmount
    number ProductionCost
    
    OpNo SubContratados
    int quantidadeSubContrato
    int DiscardedAmount
    number CustoTotal

    number CustoTotalProduto
    int ExpectedQuantity
    int MadeAmount
    int DiscardedAmount
    PerdaNo perdaNo 
    nvarchar[50] name 
    number percentagem 
    number totalPerda
    nvarchar[5] unidade
    nvarchar[9] Status 
    DateTime CreationDate
    DateTime StarDate
    DateTime EndDate
    number Priority
    nvarchar[250] Obs
    ClientNo cliente
    number CostCharged
}   

/'
O stock é quantidade que tem de Artigo
O fornecedor vai ter os campos da tabela e o Artigo 
pode ter varios

Talvez haja uma tabela materiais que liga juntamente
ao Artigo há tabela operação
'/
class Artigo {
    ProductNo ProductNo
    nvarchar[30] Name 
    number PriceUnitario 
    nvarchar[20] ProductType
    FichTecNo FichTecNo
    nvarchar[250] Descricao
    nvarchar[9] Genero
    StockNo stockNo
    number stock 
    string unidadeStock
}

/'
Conjunto de operações necessarias para a produção
de um Artigo, os materiais utilizados e o resultado 
final
'/
class FichaTecnica {
    FichTecNo FichTecNo
    FuncNo TecnicoResp 
    OpNo Operacoes
    ProductNo Materiais
    number quantidadeNecessariaEsperada
    ProductNo ProdutoFinal
    nvarchar[5] Tamanho
    number Peso
    nvarchar[30] cor
    nvarchar[250] Obs
}

/'
Parceiro externo que pode desenvolver uma operação
Ver se apenas um subContratado pode fazer uma e so uma operação
'/
class Operacao {
    OpNo OpNo 
    Type type 
    nvarchar[30] Name 
    nvarchar[250] Obs
}

/'
ExpectedTime, acho que é o unico que não é preciso

O subContratado ele manda tudo, o que está bem, mal, etc.

O productNo seria os materias que enviamos
'/
class SubContratado {
    SubContratado SubContratado
    ArtigoNo artigosEnviados
    number Quantidade
    ArtigoNo artigoRecebido
    number QuantidadeRecebido
    FornNo codForn 
    nvarchar[50] name
    PhoneNumber PhoneNumber
    char[50] email
    nvarchar[150] address
    number price 
    dateTime expectedTime 
    ProductNo produtctNo 
}

SubContratado }o--|{ Artigo: Utiliza
SubContratado }o---|| Artigo: Entrega

/'Extras se quissermos complicar'/

/'Setor da fabrica responsável por uma determinada
operacao'/
class Departamento {
    DeptNo DeptNo 
    nvarchar[30] Name
    FuncNo SupVisNo 
}

/'
Funcionario da fabrica, que faz parte de um setor
'/
class Funcionario {
    FuncNo FuncNo
    DeptNo DeptNo 
    nvarchar[20] Fname
    nvarchar[20] Lname
    Sex Sex
    nvarchar[25] Position
    number Salary
    PhoneNumber PhoneNumber 
    char[50] email
    nvarchar[150] Address
    date DOB
}

class Cliente {
    ClientNo ClientNo
    nvarchar[20] Fname
    nvarchar[20] Lname
    Sex Sex
    number NIF 
    PhoneNumber PhoneNumber 
    char[50] email
    nvarchar[150] Address 
    date DOB
    nvarchar[11] Type
}

/'
Relacionamento dos Funcionarios
'/
Funcionario }|--o| Departamento: Possui
Funcionario ||--o{ Departamento: SuperVisiona 

/'
Relacionamento das Operacoes Interna
'/
Operacao }|--o| Departamento: Realiza(da)

/'
Relacionamento Ficha Tecnica
'/
FichaTecnica }o--|{ Operacao
FichaTecnica }o--|{ Artigo: Utiliza(do)

/'
Relacionamentos do Artigo
'/
Artigo ||--|| FichaTecnica: Produto Final
FichaTecnica }o--o{ OrdemFabrico

/'
Relacionamento Ordem Fabrico
'/
OrdemFabrico }o--o| Cliente: Contrata
OrdemFabrico }o--o{ SubContratado

@enduml