@startuml tableBD

/'
!Meter realções ternarias
!Ligação da ORdem de Fabrico e Produto mal, o que liga é a ficha Tecnica
'/

class OrdemFabrico {
    ManufacturingNo ManufacturingNo
    nvarchar[9] Status 
    DateTime CreationDate
    DateTime StarDate
    DateTime EndDate
    number Priority
    nvarchar[250] Obs
    number CostCharged
}

class LinhasFichaTecnicas {
    ManufacturingNo ManufacturingNo
    FichTecNo FichTecNo
    number quantidadeProduzir
    number quantidadePerdas
}

class LinhasSubContratos {
    ManufacturingNo ManufacturingNo
    SubContratado SubContratado
    number quantidadeProduzir
    number quantidadePerdas
    dateTime expectedTime
}

class SubContratado {
    SubContratado SubContratado
    number price 
    MaterialNo materialFinal
}


class FichaTecnica {
    FichTecNo FichTecNo
    ProductNo ProductNo 
    number ProductionCost   
    nvarchar[250] Obs
}

class EtapaProducao {
    FichTecNo FichTecNo
    OpNo OpNo
    MateriaNo MaterialSaida
    int ExpectedQuantity
    int MadeAmount
    int DiscardedAmount
}

class Operacao {
    OpNo OpNo 
    nvarchar[30] Name 
    nvarchar[250] Obs
}

class OperacaoEtapa {
    FichTecNo FichTecNo
    OpNo OpNo
    MaterialNo MaterialSaida
}

class ListaMaterial {
    OpNo OpNo 
    MaterialNo MaterialSaida
    MaterialNo MaterialNo
    number quantidadeMaterial
}

class MateriaPrima {
    MateriaNo materiaNo
    nvarchar[30] Name 
    number PriceUnitario
    number stock 
    string unidadeStock
    nvarchar[250] Obs
}

class MaterialEnviado {
    SubContratadoNo SubContratado
    MaterialNo MaterialNo
    number quantidadeEnviada
}


class Produto {
    ProductNo ProductNo
    nvarchar[30] Name 
    number PriceUnitario 
    nvarchar[20] ProductType
    nvarchar[250] Descricao
    nvarchar[9] Genero
    nvarchar[5] Tamanho
    number Peso
    number stock 
    string unidadeStock
}



/'
Relacionamentos do Produto
'/
Produto ||-o{ FichaTecnica: Produto

/'
Relacionamento Etapa Producao
'/
EtapaProducao }|--|| FichaTecnica: Etapas Produção
EtapaProducao }o-|| MateriaPrima: Produto Entregue

/'
Relacionamento Intermediario Operacao Etapa
'/
OperacaoEtapa }o--|| Operacao: Operacoes Necessarias
OperacaoEtapa }|--|| EtapaProducao: Operacoes Necessarias

/'
Relacionamento Intermediario Operacao Etapa
'/
ListaMaterial }o--|| MateriaPrima: Materia Utilizado
ListaMaterial }|--|| EtapaProducao: Materia Utilizado

/'
Relacionamento Intermediario Material Enviado ao SubContrato
'/
MaterialEnviado }|--|| SubContratado: Material Enviado
MaterialEnviado }o--|| MateriaPrima: Material Enviado

/'
Relacionamento SubContrato
'/
SubContratado }o--|| MateriaPrima: Produto Final

/'
Relacionamento da Ordem de Fabrico
'/
LinhasFichaTecnicas }o-|| FichaTecnica
LinhasFichaTecnicas }|--|| OrdemFabrico

LinhasSubContratos }o--|| SubContratado
LinhasSubContratos }|--|| OrdemFabrico

@enduml