@startuml tableBD

/'
!Meter realções ternarias
!Ligação da ORdem de Fabrico e Produto mal, o que liga é a ficha Tecnica
? Um produto só pode ter uma fichaTecnica
'/

/'Estes valores
int ExpectedQuantity
    int MadeAmount
    int DiscardedAmount
são comuns para a ordem e subContratado'/
class OrdemFabrico {
    ManufacturingNo ManufacturingNo

    FichTecNo FichTecNo
    ProductNo ProductNo
    int QuantidadeEsperada
    int QuantidadeProduzida
    int QuantidadePerdia
    nvarchar[5] unidadeProduto

    SubContratadoNo SubContratadoNo
    int QuantidadeEsperada
    int QuantidadeProduzida
    int QuantidadePerdia
    nvarchar[5] unidadeSubContratado

    nvarchar[9] Status 
    DateTime CreationDate
    DateTime StarDate
    DateTime EndDate
    number Priority
    nvarchar[250] Obs
    number CostCharged
}   

/'
O stock é quantidade que tem de Produto
O fornecedor vai ter os campos da tabela e o Produto 
pode ter varios

Talvez haja uma tabela materiais que liga juntamente
ao Produto há tabela operação

ProductionType --> Acabado ou SemiAcabado 
'/
class Produto {
    ProductNo ProductNo
    nvarchar[30] Name 
    number PriceUnitario 
    nvarchar[20] ProductType
    nvarchar[20] ProductionType
    nvarchar[250] Descricao
    nvarchar[9] Genero
    number stock 
    string unidadeStock
}

/'
Meti campos que não estão no word
categoria --> grupo da matéria-prima (ex: Químicos, Metais, Plásticos)
posso meter o campos (preço unitario, depois na ligação da Operacao Materia Prima)
'/
class MateriaPrima {
    MateriaNo materiaNo
    nvarchar[30] Name 
    nvarchar[150] Descrição
    nvarchar[25] categoria
    number stock 
    string unidadeStock
}

/'
OpNo --> operação(ões) da ficha Tecnica
ProductNo --> Código do produto final
'/
class FichaTecnica {
    FichTecNo FichTecNo
    ProductNo codProdutoFinal
    number quantidadeNecessariaEsperada
    OpNo OpNo
    number tempoEsperado
    nvarchar[5] Tamanho
    number Peso
    nvarchar[30] cor
    nvarchar[250] Obs
}

/'
MateriaNo --> É o id do(s) materiai(s) utilizados na operação
ProductNo --> É o id do produto final, produzido
'/
class Operacao {
    OpNo OpNo 
    nvarchar[30] Name 
    nvarchar[250] Obs
    ProductNo codProdutoFinal
    number quantidadeEstimadaProduzida
    MateriaNo codMaterial
    number quantidadeEstimadaMateria
}

/'
MateriaNo --> É o id do(s) materiai(s) a enviar ao subContratado
ProductNo --> ´R o id do produto final, produzido
'/
class SubContratado {
    SubContratado SubContratado
    number price 
    dateTime expectedTime 
    MateriaNo MateriaNo
    number quantidadeEnviada
    ProductNo ProductNo
    number quantidadeProduzir
}


/'Extras se quissermos complicar'/

/'Setor da fabrica responsável por uma determinada
operacao'/

/'
Relacionamento dos Funcionarios
'/
 

/'
Relacionamento das Operacoes Interna
'/
Operacao }o--|{ MateriaPrima: Materiais Utilizados
Operacao }o--|| Produto: Produto Final

/'
Relacionamento Ficha Tecnica
'/
FichaTecnica }o--|{ Operacao
/'
FichaTecnica }o--|{ MateriaPrima: Utiliza(do)
'/
FichaTecnica }o--o{ OrdemFabrico

/'
Relacionamentos do Produto
'/
Produto ||--o{ FichaTecnica: Produto Final

/'
Relacionamento Ordem Fabrico
'/
OrdemFabrico }o--o{ SubContratado

/'
Relacionamento SubContrato
'/
SubContratado }o--|| Produto
SubContratado }o-o{ MateriaPrima
@enduml