@startuml tableBD

/'
!Meter realções ternarias
!Ligação da ORdem de Fabrico e Produto mal, o que liga é a ficha Tecnica
'/

class OrdemFabrico {
    nvarchar[9] Status 
    DateTime CreationDate
    DateTime StarDate
    DateTime EndDate
    number Priority
    nvarchar[250] Obs
    number CostCharged
}

class SubContratado {
    SubContratado SubContratado
    number price 
    dateTime expectedTime
    MaterialNo materialEnviado 
    number quantidadeEnviada
    MaterialNo materialFinal
    number quantidadeProduzir
    number quantidadePerdas
}

class FichaTecnica {
    FichTecNo FichTecNo
    number ProductionCost
    ProductNo ProductNo  
    int ExpectedQuantity
    int MadeAmount
    int DiscardedAmount
    number quantidadeMateria  
    nvarchar[250] Obs
}

class EtapaProducao {
    FichTecNo FichTecNo
    OpNo OpNo
}

class Produto {
    ProductNo ProductNo
    nvarchar[30] Name 
    number PriceUnitario 
    nvarchar[20] ProductType
    nvarchar[250] Descricao
    nvarchar[9] Genero
    nvarchar[5] Tamanho
    number Peso
    number stock 
    string unidadeStock
}

class MateriaPrima {
    MateriaNo materiaNo
    nvarchar[30] Name 
    number PriceUnitario
    number stock 
    string unidadeStock
    nvarchar[250] Obs
}

class Operacao {
    OpNo OpNo 
    nvarchar[30] Name 
    nvarchar[250] Obs
}

/'
Relacionamento Etapa Producao
'/
EtapaProducao }|--|| FichaTecnica: Etapas Produção
EtapaProducao }|--o{ Operacao: Operacoes Necessarias
EtapaProducao }o--|{ MateriaPrima: Materiais Necessario
EtapaProducao }o--|| MateriaPrima: Produto Entregue

/'
FichaTecnica }o--|{ MateriaPrima: Utiliza(do)
'/
FichaTecnica }|-o{ OrdemFabrico

/'
Relacionamentos do Produto
'/
Produto ||--o{ FichaTecnica: Produto Final

/'
Relacionamento Ordem Fabrico
'/
OrdemFabrico }o-o{ SubContratado

/'
Relacionamento SubContrato
'/
SubContratado }o--|| MateriaPrima: Produto Final
SubContratado }o--|{ MateriaPrima: Materias Enviados
@enduml