@startuml tableBD


class OrdemFabrico {
    ManufacturingNo ManufacturingNo
    DateTime CreationDate
    DateTime StarDate
    DateTime EndDate
    DateTime ExpectedEndDate
    int TotTimeExpected 
    int TotCostSubContract
    int Priority
    nvarchar[9] Status 
    nvarchar[250] Obs
}   

class Produto {
    ProductNo ProductNo
    nvarchar[30] Name 
    float PriceUn
    nvarchar[20] ProductType
    nvarchar[250] Description
    nchar[1] Genero
    nchar[5] Sizes
    float Weight
    int stock 
    nvarchar[5] unityStock
}

class MateriaPrima {
    MateriaNo materiaNo
    nvarchar[30] Name
    float PriceUn
    int stock 
    nchar[5] unityStock
    nvarchar[250] Obs
}

class FichaTecnica {
    FichTecNo FichTecNo 
    ProductNo ProductNo
    nvarchar[250] Obs
}

class Operacao {
    OpNo OpNo
    nvarchar[30] Name 
    nvarchar[250] Obs
}

class SubContratado {
    SubContratado SubContratado
    nvarchar[30] name
    nvarchar[250]
}

class EtapaProducao {
    FichTecNo FichTecNo
    OpNo OpNo
    MateriaNo materiaNo
    Type Type
}

class EtapasOrdem {
    FichTecNo FichTecNo
    OpNo OpNo
    int QuantityMaterialOp
    int QuantityLost
    SubContratado OpSubNo
    int QuantityMaterialSub
    int QuantityReceivedSub
    int QuantityLost
    float PriceSub
    MateriaNo materiaNo
    Type Type
    int TotQuantity 
    int TotQuantityLost 
    int Priority 
    int TimeInMinutes 
    nchar[1] Status
    int Ordem
}

/'
Relacionamento Etapa Producao
'/
EtapaProducao }|--|| FichaTecnica: Etapas Produção
EtapaProducao }o--|| Operacao: Operacoes Necessarias
EtapaProducao }o--|| MateriaPrima: Materiais Necessarios

/'
Etapas da Ordem
'/
SubContratado |o--o{ EtapasOrdem: Pode possuir 
EtapasOrdem ||--|{ EtapaProducao: Possui
OrdemFabrico ||--|{ EtapasOrdem: faz parte de


/'
Relacionamentos do Produto
'/
Produto ||--o{ FichaTecnica: descreve


@enduml