class Ordem {
    ManufactoringNo
    Dados 
}

class Operacao {
    OpNo 
    Name 
}

class Material {
    MatNo MatNo
}
 
class MaterialUtilizado {
    OpNo Operacao 
    MatNo MaterialEntrada
    QuantidadeUtilizada 
    Perdas
}

class MaterialEnviado {
    SubContratadoNo SubNo 
    MaterialEntrada 
    QuantiadadeEnviada 
    Perdas
}

class OrdemEtapas {
    SubContratado SubNo
    OpNo OpNo 
    MatNo MaterialFinal
    QuantidadeProduzidaInterna
    QuantidadeProduzidaSubContratado
    QuantidadeProduzida
    TempoTotal

}

Material ||--o{ MaterialEnviado
SubContratado ||--|{ MaterialEnviado

Ordem ||--|{ OrdemEtapas


Material ||--o{ MaterialUtilizado
Operacao ||--o{ MaterialUtilizado

OrdemEtapas ||--|{ MaterialEnviado
OrdemEtapas ||--|{ MaterialUtilizado
OrdemEtapas ||--|{ Material
