@startuml DepartamentoFuncionarios

class Departamento {
    DeptNo DeptNo 
    nvarchar[30] Name
    FuncNo SupVisNo 
}

class Funcionario {
    FuncNo FuncNo
    DeptNo DeptNo 
    nvarchar[20] Fname
    nvarchar[20] Lname
    Sex Sex
    nvarchar[25] Position
    number Salary
    PhoneNumber PhoneNumber 
    char[50] email
    nvarchar[150] Address
    date DOB
}

Funcionario }|--o| Departamento: Possui
Funcionario ||--o{ Departamento: SuperVisiona 
@enduml