@startuml Normalizacao

class Produto {
    ProductNo ProductNo
    nvarchar[30] Name 
    number PriceUnitario 
    nvarchar[20] ProductType
    nvarchar[20] ProductionType
    nvarchar[250] Descricao
    nvarchar[9] Genero
    number stock 
    string unidadeStock
}

class MateriaPrima {
    MateriaNo materiaNo
    nvarchar[30] Name 
    nvarchar[100] descricao
    nvarchar[20] categoria
    number stock 
    string unidadeStock
}

class Operacao {
    OpNo OpNo
    nvarchar[30] Name 
    nvarchar[250] Obs
    ProductNo ProductNo 
}

class MaterialUtilizado {
    OpNo OpNo 
    MateriaNo materiaNo
    number quantidadeEstimadaMaterial
}

class SubContratado {
    SubContratoNo SubContratoNo
    number TempoEstimado 
    nvarchar[5] unidadeTempo
    ProductNo ProductNo 
    number QuantidadeProduzida
    number QunatidadePerdida  
}

class MaterialEnviado {
    SubContratoNo SubContratoNo 
    MateriaNo materiaNo
    number quantidadeEnviada
}

class FichaTecnica {
    FichTecNo FichTecNo
    ProductNo ProdutoFinal
    number quantidadeNecessariaEsperada
    number tempoEsperado
    nvarchar[5] Tamanho
    number Peso
    nvarchar[30] cor
    nvarchar[250] Obs
}

class EtapaProducao {
    FichTecNo FichTecNo
    OpNo OpNo
    number QuantidadeProduzida  
    number TempoEstimado 
    nvarchar[5] unidadeTempo
}

/'
Relacionamento da FichaTecnica
'/
FichaTecnica }o---|| Produto
FichaTecnica ||--|{ EtapaProducao
Operacao ||--o{ EtapaProducao

/'
Relacionamento Operacao
'/
Operacao }o---|| Produto: ProdutoFinal
Operacao ||--|{ MaterialUtilizado: Material Enviado
MateriaPrima ||---o{ MaterialUtilizado

/'Relacionamento SubContrato'/
SubContratado }o---|| Produto: ProdutoFinal
SubContratado ||--|{ MaterialEnviado: Material Enviado
MateriaPrima ||---o{ MaterialEnviado

@end