@startuml tableBD
/'
Validar se tem todos os dados
'/

class Funcionario {
    FuncNo FuncNo
    DeptNo DeptNo
    nvarchar[20] Fname
    nvarchar[20] Lname
    Sex Sex
    nvarchar[25] Position
    number Salary
    PhoneNumber PhoneNumber
    char[50] email
    nvarchar[150] Address
    date DOB
}

class Departamento {
    DeptNo DeptNo 
    nvarchar[30] Name
    FuncNo SupVisNo 
}

Funcionario }|--o| Departamento: Possui
Funcionario ||--o{ Departamento: SuperVisiona 

class Operacao {
    OpNo OpNo
    Type type
    nvarchar[30] Name
    nvarchar[250] Obs
}

class OperacaoDepartamento {
    DeptNo DeptNo
    OpNo OpNo
}

Operacao ||--o| OperacaoDepartamento
Departamento ||--|{ OperacaoDepartamento

class Produto {
    string codProd_PK
    string Name
    float Price
    string ProducType 
    string Descricao 
    string codStock 
    float quantidade 
    string unidadeStock 
}

/'
Possui as etapas de operacoes, materiais utilizados
e o resultado
'/
class FichaTecnica {
    FichTecNo FichTecNo
    FuncNo TecnicoResp 
    OpNo Operacoes
    ProductNo Materiais
    nvarchar[5] Tamanho
    number Peso
    nvarchar[30] cor
    nvarchar[250] Obs
}

class FichaTecnicaOperacao {
    FichTecNo FichTecNo
    OpNo OpNo
}

FichaTecnica |o--|{ FichaTecnicaOperacao
Operacao ||--o{ FichaTecnicaOperacao

class ProdutoFichaTecnica {
    string codProd_PK
    string codFichaTecnica_PK
}

Produto |o--o{ ProdutoFichaTecnica: Possui
FichaTecnica |o--o{ ProdutoFichaTecnica: Utiliza

class SubContratado {
    SubContratado SubContratado
    number price 
    dateTime expectedTime 
}

class subContratoFornecedor {
    SubContratado SubContratado
    FornNo codForn
}

class Fornecedor {
    FornNo codForn 
    nvarchar[50] name
    PhoneNumber PhoneNumber
    char[50] email
    nvarchar[150] address
}

SubContratado |o--|{ subContratoFornecedor
Fornecedor ||--o{ subContratoFornecedor

class Cliente {
    ClientNo ClientNo
    nvarchar[20] Fname
    nvarchar[20] Lname
    Sex Sex
    number NIF 
    PhoneNumber PhoneNumber 
    char[50] email
    nvarchar[150] Address 
    date DOB 
    nvarchar[11] Type  
}

class OrdemFabrico {
    ManufactoringNo manufacotingNo
    codLinha codLinha
    number TotProductionCost
    number TotCostCharged
    nvarchar[9] status
    Date CreationDate
    Date StartDate
    Date EndDate
    number Priority
    number TotDiscardedAmount 
    number TotPercentagem 
    navarchar[250] Obs    
} 

class LinhaOrdemFabrico {
    CodLinha codLinha
    ManufactoringNo manufacotingNo
    ProductNo productNo
    number ExpectedQuantity
    number MadeAcount 
    nvarchar[5] unidade
    number ProductionCost 
    number CostCharged
    number CodPerdas 
    nvarchar[30] name
    nvarchar[20] type
    number DiscardedAmount 
    number Percentagem 
    nvarchar[5] unidade
}
OrdemFabrico }o--o| Cliente: Contrata

Produto ||--|{ LinhaOrdemFabrico
OrdemFabrico ||--|{ LinhaOrdemFabrico

class SubContratadoLinha {
    CodLinha codLinha
    OpNo SubContratado 
}

SubContratado |o--o{ SubContratadoLinha
LinhaOrdemFabrico |o--o{ SubContratadoLinha

@enduml