@startuml NormalizacaoOperacoes

class Produto {
    ProductNo ProductNo
    nvarchar[30] Name 
    number PriceUnitario 
    nvarchar[20] ProductType
    nvarchar[20] ProductionType
    nvarchar[250] Descricao
    nvarchar[9] Genero
    number stock 
    string unidadeStock
}

class Operacao {
    OpNo OpNo
    nvarchar[30] Name 
    nvarchar[250] Obs
    number TempoEstimado 
    nvarchar[5] unidadeTempo
    ProductNo ProductNo 
    number QuantidadeProduzida  
}

class MaterialUtilizado {
    OpNo OpNo 
    MateriaNo materiaNo
    number quantidadeEstimadaMaterial
}

class MateriaPrima {
    MateriaNo materiaNo
    nvarchar[30] Name 
    nvarchar[100] descricao
    nvarchar[20] categoria
    number stock 
    string unidadeStock
}

Operacao }o--|| Produto: ProdutoFinal
Operacao ||--|{ MaterialUtilizado: Material Enviado
MateriaPrima ||--o{ MaterialUtilizado

@end