@startuml OrdemFabricoNormalizacao

class FichaTecnica {
    FichTecNo FichTecNo
    ProductNo ProdutoFinal
    nvarchar[5] Tamanho
    number Peso
    nvarchar[30] cor
    nvarchar[250] Obs
} 

class SubContratado {
    SubContratoNo SubContratoNo
    ProductNo ProductNo 
    nvarchar[30] name
    nvarchar[125] Obs
}

class FichaTecnicaSubContratos {
    FichTecNo FichTecNo
    SubContratadoNo SubContratadoNo
    number QuantidadeProduzida
    number QunatidadePerdida
    number TempoEstimado 
    nvarchar[5] unidadeTempo
}

class OrdemFabrico {
    ManufacturingNo ManufacturingNo
    nvarchar[9] Status 
    DateTime CreationDate
    DateTime StarDate
    DateTime EndDate
    number Priority
    nvarchar[250] Obs
    number CostCharged
}

class LinhaOrdemFabrico {
    ManufacturingNo ManufacturingNo
    FichTecNo FichTecNo
    int QuantidadeProduzida
    int QuantidadePerdia
    number tempoEsperado
    nvarchar[5] unidade
}

/'
Relacionamento OrdemFabrico
'/
OrdemFabrico ||--|{ LinhaOrdemFabrico

FichaTecnicaSubContratos ||--o{ LinhaOrdemFabrico
FichaTecnica ||--o{ FichaTecnicaSubContratos

SubContratado |o--o{ FichaTecnicaSubContratos
@end