@startuml OperacaoFichaTecnica


class FichaTecnica {
    FichTecNo FichTecNo
    FuncNo TecnicoResp 
    OpNo Operacoes
    ProductNo Materiais
    nvarchar[5] Tamanho
    number Peso
    nvarchar[30] cor
    nvarchar[250] Obs
}

class Operacao {
    OpNo OpNo 
    Type type 
    nvarchar[30] Name 
    nvarchar[250] Obs
}

class FichaTecnicaOperacao {
    FichTecNo FichTecNo
    OpNo OpNo
}

FichaTecnica |o--|{ FichaTecnicaOperacao
Operacao ||--o{ FichaTecnicaOperacao

@enduml