@startuml OrdemFabrico
 
class Produto {
    ProductNo productNo
}

class OrdemFabrico {
    ManufactoringNo manufacotingNo
    codLinha codLinha
    number TotProductionCost
    number TotCostCharged
    nvarchar[9] status
    Date CreationDate
    Date StartDate
    Date EndDate
    number Priority
    number TotDiscardedAmount 
    number TotPercentagem 
    navarchar[250] Obs    
} 

class LinhaOrdemFabrico {
    CodLinha codLinha
    ManufactoringNo manufacotingNo
    ProductNo productNo
    number ExpectedQuantity
    number MadeAcount 
    nvarchar[5] unidade
    number ProductionCost 
    number CostCharged
    number CodPerdas 
    nvarchar[30] name
    nvarchar[20] type
    number DiscardedAmount 
    number Percentagem 
    nvarchar[5] unidade
}

Produto ||--|{ LinhaOrdemFabrico
OrdemFabrico ||--|{ LinhaOrdemFabrico

class SubContratado {
    OpNo SubContratado
}

class SubContratadoLinha {
    CodLinha codLinha
    OpNo SubContratado 
}

SubContratado |o--o{ SubContratadoLinha
LinhaOrdemFabrico |o--o{ SubContratadoLinha
@enduml