@startuml TabelaER_PK


class OrdemFabrico {
    ManufacturingNo ManufacturingNo
}   

class Produto {
    ProductNo ProductNo
}

class MateriaPrima {
    MateriaNo materiaNo
}

class FichaTecnica {
    FichTecNo FichTecNo 
}

class Operacao {
    OpNo OpNo
}

class SubContratado {
    SubContratado SubContratado
}

<> EtapaProducao

<> EtapasOrdem

/'
Relacionamento Etapa Producao
'/
EtapaProducao }|--|| FichaTecnica: Etapas Produção
EtapaProducao }o--|| Operacao: Operacoes Necessarias
EtapaProducao }o--|| MateriaPrima: Materiais Necessarios

/'
Relacionamento da Etpas da Ordem
'/
SubContratado ||--o{ EtapasOrdem: Pode possuir
EtapasOrdem ||--|{ EtapaProducao: Possui
OrdemFabrico ||--|{ EtapasOrdem: faz parte de

/'
Relacionamentos do Produto
'/
Produto ||--o{ FichaTecnica: descreve


@enduml