@startuml tableBD

/'
!Meter realções ternarias
!Ligação da ORdem de Fabrico e Produto mal, o que liga é a ficha Tecnica
'/

/'Estes valores
int ExpectedQuantity
    int MadeAmount
    int DiscardedAmount
são comuns para a ordem e subContratado'/
class OrdemFabrico {
    ManufacturingNo ManufacturingNo
}   

/'
O stock é quantidade que tem de Produto
O fornecedor vai ter os campos da tabela e o Produto 
pode ter varios

Talvez haja uma tabela materiais que liga juntamente
ao Produto há tabela operação

ProductionType --> Acabado ou SemiAcabado 
'/
class Produto {
    ProductNo ProductNo
}

class MateriaPrima {
    MateriaNo materiaNo
}

/'
Conjunto de operações necessarias para a produção
de um Produto, os materiais utilizados e o resultado 
final
'/
class FichaTecnica {
    FichTecNo FichTecNo
}

/'
Parceiro externo que pode desenvolver uma operação
Ver se apenas um subContratado pode fazer uma e so uma operação
'/
class Operacao {
    OpNo OpNo 
}
/'
ExpectedTime, acho que é o unico que não é preciso

O subContratado ele manda tudo, o que está bem, mal, etc.

O productNo seria os materias que enviamos
'/
class SubContratado {
    SubContratado SubContratado
}


/'Extras se quissermos complicar'/

/'Setor da fabrica responsável por uma determinada
operacao'/

/'
Relacionamento dos Funcionarios
'/
 

/'
Relacionamento das Operacoes Interna
'/
Operacao }o--|{ MateriaPrima: Materiais Utilizados
Operacao }o--|| Produto: Produto Final

/'
Relacionamento Ficha Tecnica
'/
FichaTecnica }o--|{ Operacao
/'
FichaTecnica }o--|{ MateriaPrima: Utiliza(do)
'/
FichaTecnica }o--o{ OrdemFabrico

/'
Relacionamentos do Produto
'/
Produto ||--o{ FichaTecnica: Produto Final

/'
Relacionamento Ordem Fabrico
'/
OrdemFabrico }o--o{ SubContratado

@enduml