@startuml tableBD

/'
!Meter realções ternarias
!Ligação da ORdem de Fabrico e Produto mal, o que liga é a ficha Tecnica
'/

class OrdemFabrico {
    ManufacturingNo ManufacturingNo
}   

class Produto {
    ProductNo ProductNo
}

class MateriaPrima {
    MateriaNo materiaNo
}

class FichaTecnica {
    FichTecNo FichTecNo  
}

class Operacao {
    OpNo OpNo 
}

class SubContratado {
    SubContratado SubContratado
}

class EtapaProducao {
}

/'
Relacionamento Etapa Producao
'/
EtapaProducao }|--|| FichaTecnica: Etapas Produção
EtapaProducao }|--o{ Operacao: Operacoes Necessarias
EtapaProducao }o--|{ MateriaPrima: Materiais Necessario
EtapaProducao }o--|| MateriaPrima: Produto Entregue

/'
FichaTecnica }o--|{ MateriaPrima: Utiliza(do)
'/
FichaTecnica }|-o{ OrdemFabrico

/'
Relacionamentos do Produto
'/
Produto ||--o{ FichaTecnica: Produto Final

/'
Relacionamento Ordem Fabrico
'/
OrdemFabrico }o-o{ SubContratado

/'
Relacionamento SubContrato
'/
SubContratado }o--|| MateriaPrima: Produto Final
SubContratado }o--|{ MateriaPrima: Materias Enviados
@enduml